[metrics]
daily = ["retained"]
weekly = ["retained", "active_hours", "tagged_sap_searches", "total_uri_count"]
overall = ["active_hours", "serp_ad_clicks", "organic_searches", "sap_search_count", "searches_with_ads", "tagged_follow_on_searches", "total_uri_count"]

[metrics.retained]
select_expression = "COALESCE(COUNT(document_id), 0) > 0"
data_source = "baseline"

[metrics.retained.statistics]
binomial = {}

##

[metrics.active_hours]
select_expression = "COALESCE(SUM(metrics.timespan.glean_baseline_duration.value), 0) / 3600.0"
data_source = "baseline"

[metrics.active_hours.statistics]
deciles = {}
bootstrap_mean = {}

##

[metrics.serp_ad_clicks]
select_expression = "{{agg_sum('ad_click')}}"
data_source = "mobile_search_clients_daily"

[metrics.serp_ad_clicks.statistics]
deciles = {}
bootstrap_mean = {}

##

[metrics.organic_searches]
select_expression = "{{agg_sum('organic')}}"
data_source = "mobile_search_clients_daily"

[metrics.organic_searches.statistics]
deciles = {}
bootstrap_mean = {}

##

[metrics.sap_search_count]
select_expression = "{{agg_sum('search_count')}}"
data_source = "mobile_search_clients_daily"

[metrics.sap_search_count.statistics]
deciles = {}
bootstrap_mean = {}

##

[metrics.searches_with_ads]
select_expression = "{{agg_sum('search_with_ads')}}"
data_source = "mobile_search_clients_daily"

[metrics.searches_with_ads.statistics]
deciles = {}
bootstrap_mean = {}

##

[metrics.tagged_sap_searches]
select_expression = "{{agg_sum('tagged_sap')}}"
data_source = "mobile_search_clients_daily"

[metrics.tagged_sap_searches.statistics]
deciles = {}
bootstrap_mean = {}

##

[metrics.tagged_follow_on_searches]
select_expression = "{{agg_sum('tagged_follow_on')}}"
data_source = "mobile_search_clients_daily"

[metrics.tagged_follow_on_searches.statistics]
deciles = {}
bootstrap_mean = {}

##

[metrics.total_uri_count]
select_expression = "{{agg_sum('total_uri_count')}}"
data_source = "mobile_search_clients_daily"

[metrics.total_uri_count.statistics]
deciles = {}
bootstrap_mean = {}

##

[data_sources.mobile_search_clients_daily]
from_expression = "mozdata.search.mobile_search_clients_daily"
experiments_column_type = "simple"
