[metrics]
daily = ["retained"]
weekly = ["retained", "active_hours"]
overall = ["active_hours"]

[metrics.retained]
select_expression = "COALESCE(COUNT(document_id), 0) > 0"
data_source = "baseline"

[metrics.retained.statistics]
binomial = {}

##

[metrics.active_hours]
select_expression = "COALESCE(SUM(metrics.timespan.glean_baseline_duration.value), 0) / 3600.0"
data_source = "baseline"

[metrics.active_hours.statistics]
deciles = {}
bootstrap_mean = {}
