apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: jetstream-
spec:
  entrypoint: jetstream
  onExit: export-statistics # export statistics after all analyses
  parallelism: 10
  arguments:
    parameters:
    - name: date  # set dynamically when worklfow gets deployed
  templates:
  - name: jetstream
    retryStrategy:
      limit: 2
      retryPolicy: "Always"
      backoff:
        duration: "2m"
        factor: 2
        maxDuration: "5m"
    activeDeadlineSeconds: 600   # terminate container template after 10 minutes  
    steps:
    - - name: get-active-experiments
        template: active-experiments  # return active experiments for specific date
    - - name: analyse-experiment      
        template: analyse-experiment  
        arguments:
          parameters:
          - name: experiment
            value: "{{item}}"
        withParam: "{{steps.get-active-experiments.outputs.result}}"  # process active experiments in parallel

  - name: active-experiments
    container:
      image: gcr.io/ascholtz-dev/jetstream:latest
      command: [bin/entrypoint, get-active-experiments, "--start_date={{workflow.parameters.date}}", "--end_date={{workflow.parameters.date}}"]

  - name: analyse-experiment
    inputs:
      parameters:
      - name: experiment
    container:
      image: gcr.io/ascholtz-dev/jetstream:latest
      command: [bin/entrypoint, analyse-experiment, "--experiment_config={{inputs.parameters.experiment}}", "--log-to-bigquery"]
      resources:
        requests:
          memory: 10Gi
    retryStrategy:
      limit: 3
      retryPolicy: "Always"
      backoff:
        duration: "10m"
        factor: 2
        maxDuration: "30m"

  - name: export-statistics
    container:
      image: gcr.io/ascholtz-dev/jetstream:latest
      command: [bin/entrypoint, export-statistics-to-json]
    activeDeadlineSeconds: 600   # terminate container template after 10 minutes  
