apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: jetstream-
spec:
  entrypoint: jetstream
  ttlStrategy:
    secondsAfterSuccess: 432000 # delete workflows automatically after 5 days
  arguments:
    parameters:
    - name: experiments  # set dynamically when worklfow gets deployed
    - name: project_id
    - name: dataset_id
    - name: bucket
    - name: analysis_periods_day
    - name: analysis_periods_week
    - name: analysis_periods_days28
    - name: analysis_periods_overall
    - name: image
  templates:
  - name: jetstream
    parallelism: 5  # run up to 5 containers in parallel at the same time
    inputs:
      parameters:
        - name: experiments
    steps:
    - - name: ensure-enrollments-and-analyze
        template: ensure-enrollments-and-analyze
        arguments:
          parameters:
          - name: slug
            value: "{{item.slug}}"
          - name: dates
            value: "{{item.dates}}"
          - name: image_hash
            value: "{{item.image_hash}}"
        withParam: "{{inputs.parameters.experiments}}"  # process these experiments in parallel
        continueOn:
          failed: true

  - name: ensure-enrollments-and-analyze
    inputs:
      parameters:
        - name: image_hash
        - name: slug
        - name: dates
    steps:
      - - name: ensure-enrollments
          template: ensure-enrollments
          arguments:
            parameters:
              - name: slug
                value: "{{inputs.parameters.slug}}"
              - name: image_hash
                value: "{{inputs.parameters.image_hash}}"
      - - name: analyse-and-export
          template: analyse-and-export
          arguments:
            parameters:
              - name: slug
                value: "{{inputs.parameters.slug}}"
              - name: date
                value: "{{item}}"
              - name: image_hash
                value: "{{inputs.parameters.image_hash}}"
          withParam: "{{inputs.parameters.dates}}"

  - name: ensure-enrollments
    inputs: 
      parameters:
      - name: image_hash
      - name: slug  
    container:
      image: gcr.io/moz-fx-data-experiments/{{workflow.parameters.image}}@sha256:{{inputs.parameters.image_hash}}
      command: [
        jetstream, --log_to_bigquery, ensure-enrollments, 
        "--experiment_slug={{inputs.parameters.slug}}", 
        "--dataset_id={{workflow.parameters.dataset_id}}", 
        "--project_id={{workflow.parameters.project_id}}"
      ]

  - name: analyse-experiment
    inputs:
      parameters:
      - name: image_hash
      - name: date
      - name: slug
    container:
      image: gcr.io/moz-fx-data-experiments/{{workflow.parameters.image}}@sha256:{{inputs.parameters.image_hash}}
      command: [
        jetstream, --log_to_bigquery, run,
        "--date={{inputs.parameters.date}}",
        "--experiment_slug={{inputs.parameters.slug}}",
        "--dataset_id={{workflow.parameters.dataset_id}}", 
        "--project_id={{workflow.parameters.project_id}}",
        "--bucket={{workflow.parameters.bucket}}", 
        "--analysis_periods={{workflow.parameters.analysis_periods_day}}",
        "--analysis_periods={{workflow.parameters.analysis_periods_week}}",
        "--analysis_periods={{workflow.parameters.analysis_periods_days28}}",
        "--analysis_periods={{workflow.parameters.analysis_periods_overall}}"
      ]
      resources:
        requests:
          memory: 10Gi   # make sure there is at least 10Gb of memory available for the task
        limits:
          cpu: 4  # limit to 4 cores
    retryStrategy:
      limit: 3  # execute a container max. 3x; sometimes a container run might fail due to limited resources
      retryPolicy: "Always"
      backoff:
        duration: "1m"
        factor: 2
        maxDuration: "5m"

  - name: export-statistics
    inputs:
      parameters:
        - name: image_hash
        - name: slug
    container:
      image: gcr.io/moz-fx-data-experiments/{{workflow.parameters.image}}@sha256:{{inputs.parameters.image_hash}}
      command: [
        jetstream, export-statistics-to-json, 
        "--dataset_id={{workflow.parameters.dataset_id}}", 
        "--project_id={{workflow.parameters.project_id}}",
        "--experiment_slug={{inputs.parameters.slug}}",
        "--bucket={{workflow.parameters.bucket}}"
      ]
    activeDeadlineSeconds: 600   # terminate container template after 10 minutes

  - name: analyse-and-export
    inputs:
      parameters:
        - name: slug
        - name: date
        - name: image_hash
    steps:
    - - name: analyse-experiment
        template: analyse-experiment  
        arguments:
          parameters:
          - name: slug
            value: "{{inputs.parameters.slug}}"
          - name: date
            value: "{{inputs.parameters.date}}"
          - name: image_hash
            value: "{{inputs.parameters.image_hash}}"
    - - name: export-statistics
        template: export-statistics
        arguments:
          parameters:
          - name: slug
            value: "{{inputs.parameters.slug}}"
          - name: image_hash
            value: "{{inputs.parameters.image_hash}}"
