apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: jetstream-
spec:
  entrypoint: jetstream
  onExit: export-statistics # export statistics after all analyses
  arguments:
    parameters:
    - name: date  # set dynamically when workflow gets deployed
      value: "2020-10-25"
    - name: n_threads
      value: "2"
    - name: n_workers
      value: "2"
  templates:
  - name: jetstream
    parallelism: 4  # run up to 4 containers in parallel at the same time
    steps:
    - - name: get-active-experiments
        template: get-active-experiments  # return active experiments for specific date
    - - name: analyse-experiment      
        template: analyse-experiment  
        arguments:
          parameters:
          - name: experiment
            value: "{{item}}"
        withParam: "{{steps.get-active-experiments.outputs.result}}"  # process active experiments in parallel

  - name: get-active-experiments
    container:
      image: gcr.io/ascholtz-dev/jetstream-dask:latest
      command: [bin/entrypoint, get-active-experiments, "--start_date={{workflow.parameters.date}}", "--end_date={{workflow.parameters.date}}"]
    activeDeadlineSeconds: 600   # terminate container after 10 minutes  

  - name: analyse-experiment
    inputs:
      parameters:
      - name: experiment
    container:
      image: gcr.io/ascholtz-dev/jetstream-dask:latest
      command: [bin/entrypoint, analyse-experiment, 
        "--experiment_config={{inputs.parameters.experiment}}",
        "--n_threads={{workflow.parameters.n_threads}}", 
        "--n_workers={{workflow.parameters.n_workers}}"]
      resources:
        requests:
          memory: 10Gi
        limits:
          memory: 16Gi
    retryStrategy:
      limit: 3  # execute a container max. twice; sometimes a container run might fail due to limited resources
      retryPolicy: "Always"
      backoff:
        duration: "10m"
        factor: 2
        maxDuration: "30m"

  - name: export-statistics
    container:
      image: gcr.io/ascholtz-dev/jetstream-dask:latest
      command: [bin/entrypoint, export-statistics-to-json]
    activeDeadlineSeconds: 600   # terminate container template after 10 minutes  
