apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: jetstream-
spec:
  entrypoint: jetstream
  arguments:
    parameters:
    - name: experiments  # set dynamically when worklfow gets deployed
    - name: project_id
    - name: dataset_id
    - name: bucket
  templates:
  - name: jetstream
    parallelism: 5  # run up to 5 containers in parallel at the same time
    inputs:
      parameters:
        - name: experiments
    steps:
    - - name: analyse-and-export
        template: analyse-and-export
        arguments:
          parameters:
          - name: slug
            value: "{{item.slug}}"
          - name: date
            value: "{{item.date}}"
        withParam: "{{inputs.parameters.experiments}}"  # process these experiments in parallel
        continueOn:
          failed: true

  - name: analyse-experiment
    inputs:
      parameters:
      - name: date
      - name: slug
    container:
      image: gcr.io/moz-fx-data-experiments/jetstream:latest
      command: [
        jetstream, --log_to_bigquery, run, 
        "--date={{inputs.parameters.date}}", 
        "--experiment_slug={{inputs.parameters.slug}}", 
        "--dataset_id={{workflow.parameters.dataset_id}}", 
        "--project_id={{workflow.parameters.project_id}}",
        "--bucket={{workflow.parameters.bucket}}"
      ]
      resources:
        requests:
          memory: 10Gi   # make sure there is at least 10Gb of memory available for the task
        limits:
          cpu: 4  # limit to 4 cores
    retryStrategy:
      limit: 3  # execute a container max. 3x; sometimes a container run might fail due to limited resources
      retryPolicy: "Always"
      backoff:
        duration: "1m"
        factor: 2
        maxDuration: "5m"

  - name: export-statistics
    inputs:
      parameters:
        - name: slug
    container:
      image: gcr.io/moz-fx-data-experiments/jetstream:latest
      command: [
        jetstream, export-statistics-to-json, 
        "--dataset_id={{workflow.parameters.dataset_id}}", 
        "--project_id={{workflow.parameters.project_id}}",
        "--experiment_slug={{inputs.parameters.slug}}",
        "--bucket={{workflow.parameters.bucket}}"
      ]
    activeDeadlineSeconds: 600   # terminate container template after 10 minutes

  - name: analyse-and-export
    inputs:
      parameters:
        - name: slug
        - name: date
    steps:
    - - name: analyse-experiment
        template: analyse-experiment  
        arguments:
          parameters:
          - name: slug
            value: "{{inputs.parameters.slug}}"
          - name: date
            value: "{{inputs.parameters.date}}"
    - - name: export-statistics
        template: export-statistics
        arguments:
          parameters:
          - name: slug
            value: "{{inputs.parameters.slug}}"
