apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: jetstream-
spec:
  entrypoint: jetstream
  onExit: export-statistics # export statistics after all analyses
  arguments:
    parameters:
    - name: experiments  # set dynamically when worklfow gets deployed
  templates:
  - name: jetstream
    parallelism: 5  # run up to 5 containers in parallel at the same time
    steps:
    - - name: analyse-experiment      
        template: analyse-experiment  
        arguments:
          parameters:
          - name: slug
            value: "{{item.slug}}"
          - name: date
            value: "{{item.date}}"
        withParam: "{{workflow.parameters.experiments}}"  # process these experiments in parallel

  - name: analyse-experiment
    inputs:
      parameters:
      - name: experiment
    container:
      image: gcr.io/moz-fx-data-experiments/jetstream:latest
      command: [bin/entrypoint, run, "--date={{inputs.parameters.date}}", "--experiment_slug={{inputs.parameters.slug}}"]
    retryStrategy:
      limit: 3  # execute a container max. twice; sometimes a container run might fail due to limited resources
      retryPolicy: "Always"
      backoff:
        duration: "10m"
        factor: 2
        maxDuration: "30m"

  - name: export-statistics
    container:
      image: gcr.io/moz-fx-data-experiments/jetstream:latest
      command: [bin/entrypoint, export-statistics-to-json]
    activeDeadlineSeconds: 600   # terminate container template after 10 minutes
