#!/bin/bash
pip-compile --max-rounds 20 -o - - <<< '.[testing]' |
    grep -v 'file://' |
    sed 's/pip-compile.*/update_deps/' > requirements.in

pip-compile --generate-hashes -o requirements.txt requirements.in
